/**/patrol_agent:
  ros__parameters:
    # Generic PatrolAgent parameters.
    goal_reached_wait: 3.0
    communication_delay: 0.2
    lost_message_rate: 0.0

    # MSP-specific parameters.
    msp_file: ""